{% set name = "warlock" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da0ba3f37a6a54ee6b4f6c976906ca87f6524511839d5e6d556d752f9366525f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - jsonschema >=0.7,<4
    - jsonpatch >=0.10,<2
    - six

test:
  imports:
    - warlock
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/bcwaldon/warlock
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python object model built on JSON schema and JSON patch.

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
