{% set name = "warlock" %}
{% set version = "1.3.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "1f412b1425b74ccc859d7b88eb1316928a7efbf5368eab9058a949c981dc99bc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - jsonschema >=0.7,<3
    - jsonpatch >=0.10,<2
    - six

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/bcwaldon/warlock
  license: Apache 2.0
  summary: 'Python object model built on JSON schema and JSON patch.'

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
