{% set name = "warlock" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82319ba017341e7fcdc81efc2be9dd2f8237a0da07c71476b5425651b317b1c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core

  run:
    - python >={{ python_min }}
    - jsonschema >=4
    - jsonpatch >=1,<2

test:
  imports:
    - warlock
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://github.com/bcwaldon/warlock
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python object model built on JSON schema and JSON patch.

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
